description: DecoderAug Jobs

target:
  service: sing
  name: msroctovc
  #name: msrresrchvc

environment:
  image: amlt-sing/pytorch-1.8.0-cuda11.1-cudnn8-devel

  setup:
      - rm build -rf

code:
  local_dir: $CONFIG_DIR/../

storage:
    output:
        storage_account_name: openseg
        container_name: openseg-aml
        mount_dir: /mnt/openseg_blob
        mount_options: ["-o", "attr_timeout=240"]

jobs:
  - name: baseline_without_tricks_36eps
    sku: G2
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - pwd
      - ls
      - echo "------------------------------------------------------ device information"
      - nvidia-smi
      - ls /usr/local/
      - pip list
      - echo "------------------------------------------------------ install_apps"
      - export PATH=$HOME/.local/bin:$PATH
      - python -m pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 -f https://download.pytorch.org/whl/torch_stable.html
      - python -m pip install detectron2 'git+https://github.com/facebookresearch/detectron2.git'
      - python -m pip install opencv-python einops timm azureml azureml-core azureml-sdk >/dev/null
      - python -m pip install git+https://github.com/cocodataset/panopticapi.git
      - python -m pip install git+https://github.com/mcordts/cityscapesScripts.git
      - pip install openmim==0.1.6 rich modelindex pandas scipy
      - echo "------------------------------------------------------ install mmcv"
      # - mim install mmcv-full==1.5.3
      - pip install mmcv-full==1.5.3
      - pip list
      - pip install -e .
      - pip install timm wandb
      - pip install opencv-python-headless
      - pip install numpy==1.20.2
      - pip install pycocotools==2.0.2
      - echo "------------------------------------------------------ build_repo"
      - pip install -r requirements.txt
      - echo "------------------------------------------------------ prepare_datasets"
      - sudo mkdir data
      - sudo ln -s /mnt/openseg_blob/dataset/coco data/
      - sudo ln -s /mnt/openseg_blob /blob
      - sudo ln -s /mnt/openseg_blob/jiading/pretrained_backbone pretrained_backbone
      - sudo ln -s /mnt/openseg_blob/jiading/pretrained_backbone /mnt/pretrained_backbone
      - sudo ln -s /mnt/openseg_blob/jiading/code/DecoderAug-mmdetection/mmdetection-public/work_dirs/baseline_36eps_no_tricks outputs
      - export GLOO_SOCKET_IFNAME=eth0\n
      - ls
      - bash ./tools/dist_train.sh
        configs/deformable_detr/deformable_detr_twostage_refine_r50_dim2048_16x2_36e_coco.py 2
        --work-dir outputs